//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityPatchLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommunityPatchLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Default_Abort {
            get {
                return ResourceManager.GetString("Default_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string Default_ComingSoon {
            get {
                return ResourceManager.GetString("Default_ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder is not empty.
        /// </summary>
        public static string Default_FolderIsNotEmpty {
            get {
                return ResourceManager.GetString("Default_FolderIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder is not valid.
        /// </summary>
        public static string Default_FolderSelectionError {
            get {
                return ResourceManager.GetString("Default_FolderSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Default_LanguageLabel {
            get {
                return ResourceManager.GetString("Default_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Default_LanguagePl {
            get {
                return ResourceManager.GetString("Default_LanguagePl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Default_No {
            get {
                return ResourceManager.GetString("Default_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder does not contain the Settlers 4 History Edition.
        /// </summary>
        public static string Default_NotTheSettlerFolder {
            get {
                return ResourceManager.GetString("Default_NotTheSettlerFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Default_Ok {
            get {
                return ResourceManager.GetString("Default_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Default_Save {
            get {
                return ResourceManager.GetString("Default_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Application.
        /// </summary>
        public static string Default_UpdateApplication {
            get {
                return ResourceManager.GetString("Default_UpdateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Default_Yes {
            get {
                return ResourceManager.GetString("Default_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest unstable.
        /// </summary>
        public static string Develop {
            get {
                return ResourceManager.GetString("Develop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any builds on the given branch.
        /// </summary>
        public static string Dialog_GetRemoteNoBuildsFound {
            get {
                return ResourceManager.GetString("Dialog_GetRemoteNoBuildsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like there was a timeout or you did lost the Internet connection.
        /// </summary>
        public static string Dialog_GetRemoteTimeout {
            get {
                return ResourceManager.GetString("Dialog_GetRemoteTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while getting the remote version
        ///
        ///{exception}.
        /// </summary>
        public static string Dialog_GetRemoteVersionError {
            get {
                return ResourceManager.GetString("Dialog_GetRemoteVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information.
        /// </summary>
        public static string Dialog_UpdateInformationTitle {
            get {
                return ResourceManager.GetString("Dialog_UpdateInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem while trying to update.
        /// </summary>
        public static string Dialog_UpdateProblemTitle {
            get {
                return ResourceManager.GetString("Dialog_UpdateProblemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to upgrade?.
        /// </summary>
        public static string Dialog_UpgradeTitle {
            get {
                return ResourceManager.GetString("Dialog_UpgradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Document was loaded from cache.
        /// </summary>
        public static string DocumentCacheNotice {
            get {
                return ResourceManager.GetString("DocumentCacheNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download or installation was aborted by user!.
        /// </summary>
        public static string Download_United_Aborted {
            get {
                return ResourceManager.GetString("Download_United_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the update ....
        /// </summary>
        public static string Download_United_Update {
            get {
                return ResourceManager.GetString("Download_United_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string MainWindow_Changelog {
            get {
                return ResourceManager.GetString("MainWindow_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string MainWindow_Chat {
            get {
                return ResourceManager.GetString("MainWindow_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string MainWindow_Disclaimer {
            get {
                return ResourceManager.GetString("MainWindow_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string MainWindow_Editor {
            get {
                return ResourceManager.GetString("MainWindow_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string MainWindow_FAQ {
            get {
                return ResourceManager.GetString("MainWindow_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD Patch.
        /// </summary>
        public static string MainWindow_HDPatchCategory {
            get {
                return ResourceManager.GetString("MainWindow_HDPatchCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainWindow_Help {
            get {
                return ResourceManager.GetString("MainWindow_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainWindow_Home {
            get {
                return ResourceManager.GetString("MainWindow_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellectual property.
        /// </summary>
        public static string MainWindow_IntellectualProperty {
            get {
                return ResourceManager.GetString("MainWindow_IntellectualProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string MainWindow_License {
            get {
                return ResourceManager.GetString("MainWindow_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string MainWindow_Maps {
            get {
                return ResourceManager.GetString("MainWindow_Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string MainWindow_Mods {
            get {
                return ResourceManager.GetString("MainWindow_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer.
        /// </summary>
        public static string MainWindow_Multiplayer {
            get {
                return ResourceManager.GetString("MainWindow_Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string MainWindow_News {
            get {
                return ResourceManager.GetString("MainWindow_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open User Map Folder.
        /// </summary>
        public static string MainWindow_OpenMPMapFolder {
            get {
                return ResourceManager.GetString("MainWindow_OpenMPMapFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string MainWindow_Play {
            get {
                return ResourceManager.GetString("MainWindow_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search players.
        /// </summary>
        public static string MainWindow_PlayerSearch {
            get {
                return ResourceManager.GetString("MainWindow_PlayerSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked.
        /// </summary>
        public static string MainWindow_Ranked {
            get {
                return ResourceManager.GetString("MainWindow_Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report issue.
        /// </summary>
        public static string MainWindow_ReportIssue {
            get {
                return ResourceManager.GetString("MainWindow_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Savefolder.
        /// </summary>
        public static string MainWindow_SaveFolder {
            get {
                return ResourceManager.GetString("MainWindow_SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S4 HE Config.
        /// </summary>
        public static string MainWindow_SettlersConfig {
            get {
                return ResourceManager.GetString("MainWindow_SettlersConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string MainWindow_SocialMedia {
            get {
                return ResourceManager.GetString("MainWindow_SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settle.
        /// </summary>
        public static string MainWindow_StartSettle {
            get {
                return ResourceManager.GetString("MainWindow_StartSettle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string MainWindow_Team {
            get {
                return ResourceManager.GetString("MainWindow_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Changer.
        /// </summary>
        public static string MainWindow_TextureChanger {
            get {
                return ResourceManager.GetString("MainWindow_TextureChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Patch Launcher.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MainWindow_Tools {
            get {
                return ResourceManager.GetString("MainWindow_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your local version is newer or up to date.
        /// </summary>
        public static string Message_LocalVersionIsNewer {
            get {
                return ResourceManager.GetString("Message_LocalVersionIsNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote version is newer do you want to upgrade?
        ///
        ///Local version: {localVersion}
        ///Remote version: {remoteVersion}.
        /// </summary>
        public static string Message_Update {
            get {
                return ResourceManager.GetString("Message_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get local or remote version!
        ///
        ///Is your computer offline?.
        /// </summary>
        public static string Message_VersionUpdateWarning {
            get {
                return ResourceManager.GetString("Message_VersionUpdateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all the patches for the offline mode.
        /// </summary>
        public static string PlayControl_DownloadAllPatchesTooltip {
            get {
                return ResourceManager.GetString("PlayControl_DownloadAllPatchesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Speed (2).
        /// </summary>
        public static string PlayControl_FastSpeed {
            get {
                return ResourceManager.GetString("PlayControl_FastSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch game.
        /// </summary>
        public static string PlayControl_Launch {
            get {
                return ResourceManager.GetString("PlayControl_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Speed (1).
        /// </summary>
        public static string PlayControl_NormalSpeed {
            get {
                return ResourceManager.GetString("PlayControl_NormalSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Speed (60).
        /// </summary>
        public static string PlayControl_TestingSpeed {
            get {
                return ResourceManager.GetString("PlayControl_TestingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Fast Speed (3).
        /// </summary>
        public static string PlayControl_VeryFastSpeed {
            get {
                return ResourceManager.GetString("PlayControl_VeryFastSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom size.
        /// </summary>
        public static string ResizeWindow_CustomSize {
            get {
                return ResourceManager.GetString("ResizeWindow_CustomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter window height.
        /// </summary>
        public static string ResizeWindow_HeightTooltip {
            get {
                return ResourceManager.GetString("ResizeWindow_HeightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new size.
        /// </summary>
        public static string ResizeWindow_NewSize {
            get {
                return ResourceManager.GetString("ResizeWindow_NewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new size:.
        /// </summary>
        public static string ResizeWindow_SelectNewSize {
            get {
                return ResourceManager.GetString("ResizeWindow_SelectNewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Window.
        /// </summary>
        public static string ResizeWindow_Title {
            get {
                return ResourceManager.GetString("ResizeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter window width.
        /// </summary>
        public static string ResizeWindow_WidthTooltip {
            get {
                return ResourceManager.GetString("ResizeWindow_WidthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to Settlers United (Beta).
        /// </summary>
        public static string Setters_United_Beta {
            get {
                return ResourceManager.GetString("Setters_United_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize launcher on game start.
        /// </summary>
        public static string SettingsWindow_MinimizeOnGameStart {
            get {
                return ResourceManager.GetString("SettingsWindow_MinimizeOnGameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Branch:.
        /// </summary>
        public static string SettingsWindow_UpdateBranch {
            get {
                return ResourceManager.GetString("SettingsWindow_UpdateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update on Startup.
        /// </summary>
        public static string SettingWindow_CheckForUpdateOnStartup {
            get {
                return ResourceManager.GetString("SettingWindow_CheckForUpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download folder:.
        /// </summary>
        public static string SettingWindow_DownloadFolder {
            get {
                return ResourceManager.GetString("SettingWindow_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open download folder.
        /// </summary>
        public static string SettingWindow_OpenDownloadFolder {
            get {
                return ResourceManager.GetString("SettingWindow_OpenDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open game folder.
        /// </summary>
        public static string SettingWindow_OpenGameFolder {
            get {
                return ResourceManager.GetString("SettingWindow_OpenGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open setting folder.
        /// </summary>
        public static string SettingWindow_OpenSettingFolder {
            get {
                return ResourceManager.GetString("SettingWindow_OpenSettingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset agreement.
        /// </summary>
        public static string SettingWindow_ResetAgreement {
            get {
                return ResourceManager.GetString("SettingWindow_ResetAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Please patch to History Edition first.
        ///The Community Balance Patch can be reactivated in Settlers United (in the game itself) afterwards..
        /// </summary>
        public static string Upgrade_Note {
            get {
                return ResourceManager.GetString("Upgrade_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did read the agreement.
        /// </summary>
        public static string WelcomeWindow_Agree {
            get {
                return ResourceManager.GetString("WelcomeWindow_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto detect.
        /// </summary>
        public static string WelcomeWindow_AutoDetect {
            get {
                return ResourceManager.GetString("WelcomeWindow_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string WelcomeWindow_ManuelSelection {
            get {
                return ResourceManager.GetString("WelcomeWindow_ManuelSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement.
        /// </summary>
        public static string WelcomeWindow_TextBox {
            get {
                return ResourceManager.GetString("WelcomeWindow_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeWindow_Title {
            get {
                return ResourceManager.GetString("WelcomeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game folder:.
        /// </summary>
        public static string WelcomWindow_GameFolder {
            get {
                return ResourceManager.GetString("WelcomWindow_GameFolder", resourceCulture);
            }
        }
    }
}
