//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityPatchLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommunityPatchLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort ähnelt.
        /// </summary>
        public static string Default_Abort {
            get {
                return ResourceManager.GetString("Default_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coming soon ähnelt.
        /// </summary>
        public static string Default_ComingSoon {
            get {
                return ResourceManager.GetString("Default_ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The folder is not empty ähnelt.
        /// </summary>
        public static string Default_FolderIsNotEmpty {
            get {
                return ResourceManager.GetString("Default_FolderIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected folder is not valid ähnelt.
        /// </summary>
        public static string Default_FolderSelectionError {
            get {
                return ResourceManager.GetString("Default_FolderSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        public static string Default_LanguageLabel {
            get {
                return ResourceManager.GetString("Default_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polish ähnelt.
        /// </summary>
        public static string Default_LanguagePl {
            get {
                return ResourceManager.GetString("Default_LanguagePl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string Default_No {
            get {
                return ResourceManager.GetString("Default_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected folder does not contain the Settlers 4 History Edition ähnelt.
        /// </summary>
        public static string Default_NotTheSettlerFolder {
            get {
                return ResourceManager.GetString("Default_NotTheSettlerFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string Default_Ok {
            get {
                return ResourceManager.GetString("Default_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Default_Save {
            get {
                return ResourceManager.GetString("Default_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Application ähnelt.
        /// </summary>
        public static string Default_UpdateApplication {
            get {
                return ResourceManager.GetString("Default_UpdateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Default_Yes {
            get {
                return ResourceManager.GetString("Default_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Newest unstable ähnelt.
        /// </summary>
        public static string Develop {
            get {
                return ResourceManager.GetString("Develop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find any builds on the given branch ähnelt.
        /// </summary>
        public static string Dialog_GetRemoteNoBuildsFound {
            get {
                return ResourceManager.GetString("Dialog_GetRemoteNoBuildsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seems like there was a timeout or you did lost the Internet connection ähnelt.
        /// </summary>
        public static string Dialog_GetRemoteTimeout {
            get {
                return ResourceManager.GetString("Dialog_GetRemoteTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while getting the remote version
        ///
        ///{exception} ähnelt.
        /// </summary>
        public static string Dialog_GetRemoteVersionError {
            get {
                return ResourceManager.GetString("Dialog_GetRemoteVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update information ähnelt.
        /// </summary>
        public static string Dialog_UpdateInformationTitle {
            get {
                return ResourceManager.GetString("Dialog_UpdateInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem while trying to update ähnelt.
        /// </summary>
        public static string Dialog_UpdateProblemTitle {
            get {
                return ResourceManager.GetString("Dialog_UpdateProblemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to upgrade? ähnelt.
        /// </summary>
        public static string Dialog_UpgradeTitle {
            get {
                return ResourceManager.GetString("Dialog_UpgradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Document was loaded from cache ähnelt.
        /// </summary>
        public static string DocumentCacheNotice {
            get {
                return ResourceManager.GetString("DocumentCacheNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changelog ähnelt.
        /// </summary>
        public static string MainWindow_Changelog {
            get {
                return ResourceManager.GetString("MainWindow_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chat ähnelt.
        /// </summary>
        public static string MainWindow_Chat {
            get {
                return ResourceManager.GetString("MainWindow_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disclaimer ähnelt.
        /// </summary>
        public static string MainWindow_Disclaimer {
            get {
                return ResourceManager.GetString("MainWindow_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editor ähnelt.
        /// </summary>
        public static string MainWindow_Editor {
            get {
                return ResourceManager.GetString("MainWindow_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FAQ ähnelt.
        /// </summary>
        public static string MainWindow_FAQ {
            get {
                return ResourceManager.GetString("MainWindow_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string MainWindow_Help {
            get {
                return ResourceManager.GetString("MainWindow_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string MainWindow_Home {
            get {
                return ResourceManager.GetString("MainWindow_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intellectual property ähnelt.
        /// </summary>
        public static string MainWindow_IntellectualProperty {
            get {
                return ResourceManager.GetString("MainWindow_IntellectualProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License ähnelt.
        /// </summary>
        public static string MainWindow_License {
            get {
                return ResourceManager.GetString("MainWindow_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maps ähnelt.
        /// </summary>
        public static string MainWindow_Maps {
            get {
                return ResourceManager.GetString("MainWindow_Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mods ähnelt.
        /// </summary>
        public static string MainWindow_Mods {
            get {
                return ResourceManager.GetString("MainWindow_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Multiplayer Mapfolder ähnelt.
        /// </summary>
        public static string MainWindow_MPFolder {
            get {
                return ResourceManager.GetString("MainWindow_MPFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiplayer ähnelt.
        /// </summary>
        public static string MainWindow_Multiplayer {
            get {
                return ResourceManager.GetString("MainWindow_Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die News ähnelt.
        /// </summary>
        public static string MainWindow_News {
            get {
                return ResourceManager.GetString("MainWindow_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Multiplayer Map Folder ähnelt.
        /// </summary>
        public static string MainWindow_OpenMPMapFolder {
            get {
                return ResourceManager.GetString("MainWindow_OpenMPMapFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        public static string MainWindow_Play {
            get {
                return ResourceManager.GetString("MainWindow_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search players ähnelt.
        /// </summary>
        public static string MainWindow_PlayerSearch {
            get {
                return ResourceManager.GetString("MainWindow_PlayerSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ranked ähnelt.
        /// </summary>
        public static string MainWindow_Ranked {
            get {
                return ResourceManager.GetString("MainWindow_Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report issue ähnelt.
        /// </summary>
        public static string MainWindow_ReportIssue {
            get {
                return ResourceManager.GetString("MainWindow_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Savefolder ähnelt.
        /// </summary>
        public static string MainWindow_SaveFolder {
            get {
                return ResourceManager.GetString("MainWindow_SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S4 HE Config ähnelt.
        /// </summary>
        public static string MainWindow_SettlersConfig {
            get {
                return ResourceManager.GetString("MainWindow_SettlersConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Social Media ähnelt.
        /// </summary>
        public static string MainWindow_SocialMedia {
            get {
                return ResourceManager.GetString("MainWindow_SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settle ähnelt.
        /// </summary>
        public static string MainWindow_StartSettle {
            get {
                return ResourceManager.GetString("MainWindow_StartSettle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team ähnelt.
        /// </summary>
        public static string MainWindow_Team {
            get {
                return ResourceManager.GetString("MainWindow_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Texture Changer ähnelt.
        /// </summary>
        public static string MainWindow_TextureChanger {
            get {
                return ResourceManager.GetString("MainWindow_TextureChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Community Patch Launcher ähnelt.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        public static string MainWindow_Tools {
            get {
                return ResourceManager.GetString("MainWindow_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your local version is newer or up to date ähnelt.
        /// </summary>
        public static string Message_LocalVersionIsNewer {
            get {
                return ResourceManager.GetString("Message_LocalVersionIsNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remote version is newer do you want to upgrade?
        ///
        ///Local version: {localVersion}
        ///Remote version: {remoteVersion} ähnelt.
        /// </summary>
        public static string Message_Update {
            get {
                return ResourceManager.GetString("Message_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not get local or remote version!
        ///
        ///Is your computer offline? ähnelt.
        /// </summary>
        public static string Message_VersionUpdateWarning {
            get {
                return ResourceManager.GetString("Message_VersionUpdateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download all the patches for the offline mode ähnelt.
        /// </summary>
        public static string PlayControl_DownloadAllPatchesTooltip {
            get {
                return ResourceManager.GetString("PlayControl_DownloadAllPatchesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fast Speed (2) ähnelt.
        /// </summary>
        public static string PlayControl_FastSpeed {
            get {
                return ResourceManager.GetString("PlayControl_FastSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Launch game ähnelt.
        /// </summary>
        public static string PlayControl_Launch {
            get {
                return ResourceManager.GetString("PlayControl_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal Speed (1) ähnelt.
        /// </summary>
        public static string PlayControl_NormalSpeed {
            get {
                return ResourceManager.GetString("PlayControl_NormalSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Testing Speed (60) ähnelt.
        /// </summary>
        public static string PlayControl_TestingSpeed {
            get {
                return ResourceManager.GetString("PlayControl_TestingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Very Fast Speed (3) ähnelt.
        /// </summary>
        public static string PlayControl_VeryFastSpeed {
            get {
                return ResourceManager.GetString("PlayControl_VeryFastSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Release ähnelt.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom size ähnelt.
        /// </summary>
        public static string ResizeWindow_CustomSize {
            get {
                return ResourceManager.GetString("ResizeWindow_CustomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter window height ähnelt.
        /// </summary>
        public static string ResizeWindow_HeightTooltip {
            get {
                return ResourceManager.GetString("ResizeWindow_HeightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter new size ähnelt.
        /// </summary>
        public static string ResizeWindow_NewSize {
            get {
                return ResourceManager.GetString("ResizeWindow_NewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select new size: ähnelt.
        /// </summary>
        public static string ResizeWindow_SelectNewSize {
            get {
                return ResourceManager.GetString("ResizeWindow_SelectNewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resize Window ähnelt.
        /// </summary>
        public static string ResizeWindow_Title {
            get {
                return ResourceManager.GetString("ResizeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter window width ähnelt.
        /// </summary>
        public static string ResizeWindow_WidthTooltip {
            get {
                return ResourceManager.GetString("ResizeWindow_WidthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize launcher on game start ähnelt.
        /// </summary>
        public static string SettingsWindow_MinimizeOnGameStart {
            get {
                return ResourceManager.GetString("SettingsWindow_MinimizeOnGameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Branch: ähnelt.
        /// </summary>
        public static string SettingsWindow_UpdateBranch {
            get {
                return ResourceManager.GetString("SettingsWindow_UpdateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for update on Startup ähnelt.
        /// </summary>
        public static string SettingWindow_CheckForUpdateOnStartup {
            get {
                return ResourceManager.GetString("SettingWindow_CheckForUpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download folder: ähnelt.
        /// </summary>
        public static string SettingWindow_DownloadFolder {
            get {
                return ResourceManager.GetString("SettingWindow_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open download folder ähnelt.
        /// </summary>
        public static string SettingWindow_OpenDownloadFolder {
            get {
                return ResourceManager.GetString("SettingWindow_OpenDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open game folder ähnelt.
        /// </summary>
        public static string SettingWindow_OpenGameFolder {
            get {
                return ResourceManager.GetString("SettingWindow_OpenGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open setting folder ähnelt.
        /// </summary>
        public static string SettingWindow_OpenSettingFolder {
            get {
                return ResourceManager.GetString("SettingWindow_OpenSettingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset agreement ähnelt.
        /// </summary>
        public static string SettingWindow_ResetAgreement {
            get {
                return ResourceManager.GetString("SettingWindow_ResetAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I did read the agreement ähnelt.
        /// </summary>
        public static string WelcomeWindow_Agree {
            get {
                return ResourceManager.GetString("WelcomeWindow_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto detect ähnelt.
        /// </summary>
        public static string WelcomeWindow_AutoDetect {
            get {
                return ResourceManager.GetString("WelcomeWindow_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... ähnelt.
        /// </summary>
        public static string WelcomeWindow_ManuelSelection {
            get {
                return ResourceManager.GetString("WelcomeWindow_ManuelSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Agreement ähnelt.
        /// </summary>
        public static string WelcomeWindow_TextBox {
            get {
                return ResourceManager.GetString("WelcomeWindow_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome ähnelt.
        /// </summary>
        public static string WelcomeWindow_Title {
            get {
                return ResourceManager.GetString("WelcomeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game folder: ähnelt.
        /// </summary>
        public static string WelcomWindow_GameFolder {
            get {
                return ResourceManager.GetString("WelcomWindow_GameFolder", resourceCulture);
            }
        }
    }
}
